ip_range = '192.168.50'
nodes = 2

$script = <<SCRIPT
swapoff -a
if [ ! -d /home/vagrant/.ssh ]; then mkdir /home/vagrant/.ssh; fi
echo $(cat /vagrant/tmp/id_rsa.pub) >> /home/vagrant/.ssh/authorized_keys
chmod 600 /home/vagrant/.ssh/authorized_keys && chmod 700 /home/vagrant/.ssh
sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.5 0
SCRIPT

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.cpus = 2
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :machine
    config.cache.auto_detect = false
    config.cache.enable :apt
  end

#  config.vm.define "router" do |rt|
#    rt.vm.box = "eugenmayer/opnsense"
#  end

  config.vm.define "master" do |km|
    km.vm.hostname = "vk8s-master"
    km.vm.network "private_network", ip: "#{ip_range}.10"
    km.vm.provision "shell", inline: $script
  end

  (1..nodes).each do |i|
    config.vm.define "worker-#{i}" do |node|
      node.vm.hostname = "vk8s-worker-01"
      node.vm.network "private_network", ip: "#{ip_range}.#{10 + i}"
      node.vm.provision "shell", inline: $script
    end
   end

end
